---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)

disasters = read_csv("./data/DisasterDeclarationsSummaries2.csv") %>% 
  janitor::clean_names() %>% 
  mutate(incident_type = factor(incident_type), 
       fips_state_code = fips_state_code*100) %>% 
  rename(
     year = fy_declared, 
     disaster = incident_type) %>% 
  filter(year <= 2018) %>% 
  select(fips_state_code, year, disaster) 
```

# Motivation
According to the United States Geological Survey, scientists predict that increasing global surface temperatures will increase the frequency of droughts and intensity of storms globally. Recent studies examining sea-level rise patterns and projections (Hauer, 2017; Kulp & Strauss, 2019) have suggested that sea-level rise could induce large-scale migration in the United States away from unprotected coastlines and towards inland areas, redistributing population density across the country. The potential impacts of climate change are far-reaching, ranging from human migration and displacement to increased pressure on inland areas and land disturbance. We are interested in examining if there is an association between indicators of climate change (temperature and precipitation) and the frequency of natural disasters in the United States since 1953.

# Related Work
Oddly enough, the initial inspiration for this work actually came from the coveted p8105 Cow Sticker. Our original project idea was going to revolve around cows but our discussions of cows quickly shifted to methane gas and the effects it has on our planet. As a result, we pivoted to examining climate change and natural disasters. Additionally, our work with NOAA data in class, seeing first hand how in-depth that dataset is, gave us an early understanding of the possibilities achievable with such varied data. 

In the news, climate change has been a hot topic of conversation, particularly surrounding increasing global temperatures and increased intensity of natural disasters. We have seen setbacks and progress made recently. Under the Trump Administration, the United States will pull out of the Paris Agreement as of November 4, 2020. Our group personally discussed the implications of this policy and we voiced our concerns while discussing project idases. However, there are people out there doing fantastic work in the fight for our planet, and we hope to do our part. Recently, Greta Thunberg visited NYC for the Climate Strike on September 20, 2019. An estimated 60,000 people participated in NYC while millions joined globally. We are inspired by this action by young people and hope it motivates others to join the cause. We hope our findings can do just a small part in this movement. And maybe get a sticker with a cow on it if we get a little creative along the way.

# Initial Questions
We first want to know if the total count of natural disasters are increasing every five years between 1953-2018 in the United States. We also want to know if average, minimum, and maximum land temperatures are increasing with certain natural disasters over time, examining the states where the frequency of natural disasters does significantly increase with temperature in greater detail. We will fit a multivariable regression model to address our question of whether the United States overall is seeing more natural disasters over time, then create multiple data visualizations to assess state-by-state differences.

# Data Source
Our team used a publicly available dataset called the ["Disaster Declarations Summary"](https://www.fema.gov/media-library/assets/documents/28318) (Version 2) from the Federal Emergency Management Agency (FEMA). This dataset contains summary level data on disaster declarations from 1953 to March 2019 by state and includes all three types of disaster declarations: major disaster, emergency, and fire 
management assistance. 

For the climate change indicators, we will use publicly available data from the National Oceanic and Atmospheric Administration (NOAA). We will pull data on average, maximum and minimum temperature and total precipitation by month by state from 1895. These values came from [NOAA's Climate at a Glance](https://www.ncdc.noaa.gov/cag/national/mapping/) data.

## Data Cleaning
* **Disaster Declarations Summary**: This data set was downloaded as a .csv file and imported into R. After cleaning the variable names and converting appropriate variables to factors, we renamed several variables and kept information on `State FIP Codes`, `Disaster Year` and `Disaster Type`. Overall, there were `r disasters %>% nrow()` disasters delared to FEMA from `r disasters %>% summarize(min = min(year)) %>% pull(min)` to `r disasters %>% summarize(max = max(year)) %>% pull(max)`. 

* **Climate Indicators**: These data sets were downloaded from NOAA's website directly. Data on average temperature, minimum temperature, maximum temperature, and total precipitation were recorded for year month by State since 1853. After pulling the data and cleaning variable names, the date fields were split into "Month" and "Year". Next, data were grouped by state and year and summarized as described below: 
  + **Average Temperature** The average temperature by state across all 12 months per year was summarized. 
  + **Minimum Temperature**: The minimum temperature by state across all 12 months per year was summarized. 
  + **Maximum Temperature**: The maximum temperature by state across all 12 months per year was summarized. 
  + **Total Precipitation**: The total precipation by state across all 12 months per year was totaled. 
  
## Final Data Set
Data on climate change indicators across 4 data sets were inner joined by `Location`, `Year`, and `FIPS State Code`. This created a data set with average temperature, maximum temperature, minimum temperature, and total precipitation by state and year from 1853-2018. Then, this data set was full joined to the disaster data set which had rows for each disaster by Year and State. Last a count of natural disasters was taken by year. The resulting data set had `INSERT INLINE CODE ONCE DATA SET IS LOADED`


## Data Challenges
Overall the data we pulled was easily cleaned and imported. However, we did have a major issue with data availability. From 11/25/2019-11/29/2019, the NOAA data was unavailable due to scheduled maintenance. Because we pulled all of our climate data directly from the NOAA website, we were unable to work on this final project for 5 days. While this created some last minute stress, it did not ultimately affect our work product.  

# Exploratory Analysis

# Additional Analysis 
Cows!!

# Discussion




Contributors: Holly Finertie | Matt Curran | Jana Lee | Ashley Tseng | Lulu Zhang