---
title: "Secret Cow Visualization"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    code_folding: hide
---
# Moo

```{r setup, echo=FALSE, warning = FALSE, message=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)
library(rvest)

# read in data
ave_temp = read_csv("https://www.ncdc.noaa.gov/cag/statewide/mapping/110-tavg.csv", skip = 3) %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month"), sep = 4) %>%
  mutate(
    year = as.numeric(year), 
    state_code = setNames(state.abb, state.name)[location]) %>% 
  filter(year >= 1953 & year <= 2018) %>% 
  group_by(location, year) %>% 
  mutate(
    mean_temp = mean(value)) %>% 
  dplyr::select(state_code, location, year, mean_temp) %>% 
  distinct()

precip = read_csv("https://www.ncdc.noaa.gov/cag/statewide/mapping/110-pcp.csv", skip = 3) %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month"), sep = 4) %>%
 mutate(
    year = as.numeric(year), 
    state_code = setNames(state.abb, state.name)[location]) %>% 
  filter(year >= 1953 & year <= 2018) %>% 
  group_by(location, year) %>% 
  mutate(
    total_precip = sum(value)) %>% 
  dplyr::select(state_code, location, year, total_precip) %>% 
  distinct()

tmax = read_csv("https://www.ncdc.noaa.gov/cag/statewide/mapping/110-tmax.csv", skip = 3) %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month"), sep = 4) %>%
 mutate(
    year = as.numeric(year), 
    state_code = setNames(state.abb, state.name)[location]) %>% 
  filter(year >= 1953 & year <= 2018) %>% 
  group_by(location, year) %>% 
  mutate(
    max_temp = max(value)) %>% 
  dplyr::select(state_code, location, year, max_temp) %>% 
  distinct()

tmin = read_csv("https://www.ncdc.noaa.gov/cag/statewide/mapping/110-tmin.csv", skip = 3)  %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month"), sep = 4) %>%
 mutate(
    year = as.numeric(year), 
    state_code = setNames(state.abb, state.name)[location]) %>% 
  filter(year >= 1953 & year <= 2018) %>% 
  group_by(location, year) %>% 
  mutate(
    min_temp = min(value)) %>% 
  dplyr::select(state_code, location, year, min_temp) %>% 
  distinct()

disasters = read_csv("./data/DisasterDeclarationsSummaries2.csv") %>% 
  janitor::clean_names() %>% 
  mutate(disaster = factor(incident_type)) %>% 
  rename(
     year = fy_declared) %>% 
  filter(year >= 1953 & year <= 2018) %>% 
  count(state, year, disaster) %>%
  group_by(year, state) %>% 
  mutate(
    n_state = sum(n)
  ) %>% 
  group_by(year) %>% 
  mutate(
    n_total = sum(n)
  ) %>% 
  group_by(year, disaster) %>% 
  mutate(
    n_type = sum(n)
  ) %>% 
  rename("n_disaster_state" = "n") 

final_data = 
  inner_join(ave_temp, precip, by = c("location" = "location", "year" = "year", "state_code" = "state_code")) %>% 
  inner_join(tmax, by = c("location" = "location", "year" = "year", "state_code" = "state_code")) %>% 
  inner_join(tmin, by = c("location" = "location", "year" = "year", "state_code" = "state_code")) %>% 
  full_join(disasters, by = c("year" = "year", "state_code" = "state"))
```

```{r data, message=FALSE, warning=FALSE}
disaster_data_new = final_data %>%
  ungroup(location) %>%
  group_by(year) %>%
  dplyr::select(year, n_total) %>%
  distinct(year, n_total) %>%
  drop_na()

cow_data = read_csv("./data/cow_data.csv")  %>% 
  janitor::clean_names() %>%
  dplyr::select(year, cattle_calf_crop_measured_in_head_b_value_b) %>%
  rename(total_cows_usa = cattle_calf_crop_measured_in_head_b_value_b) %>%
  inner_join(disaster_data_new, by = "year") %>%
  drop_na()
```

```{r plot, message=FALSE, warning=FALSE}
library(grid)

dis_plot = cow_data %>%
  ggplot(aes(x = year, y = n_total)) +
  geom_line(alpha = 0.2, color="blue")+
  geom_smooth(se = FALSE, color="blue")+
  labs(title = "ARE THE COWS TO BLAME: A Visualization of Disaster and Cow Trends",
       x = "Year",
       y = "Total Annual Disasters")

cow_plot = cow_data %>%
  ggplot(aes(x = year, y = total_cows_usa)) +
  geom_line(alpha = 0.2, color="red")+
  geom_smooth(se = FALSE, color="red")+
  labs(x = "Year",
      y = "Total Cows")
```

```{r message=FALSE, warning=FALSE}
grid.newpage()
grid.draw(rbind(ggplotGrob(dis_plot), ggplotGrob(cow_plot), size = "last"))
```


* Based on these plots, the cows are not at fault. The search contimoos.

* [Data taken from the USDA and found here](https://quickstats.nass.usda.gov/results/1913D0FB-63A8-3CF5-82E8-DBD5A439C547)