---
title: "Summary Visualizations"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

```{r}
library(tidyverse)
library(ggridges)
```

```{r, scatterplot}
final_data
final_data %>% 
  ggplot(aes(x = min_temp, y = max_temp))+
  geom_point(aes(color = year))+
  geom_smooth(color = "red", se = FALSE)+
  labs(title = "Minimum Temp vs. Maximum Temp Plot (F)", 
       xlab = "Minimum Temperature",
       ylab = "Maximum Temperature")+
  theme_bw()+
  theme(legend.position = "bottom")
```

```{r, density}
final_data %>% 
  filter(disaster == "Flood", total_precip > 60.0) %>% 
  ggplot(aes(x = year, fill = location)) +
  geom_density(alpha = 0.4, adjust = .5, color = "blue")+
  labs(title = "Distribution of Floods from 1953-2018 in the US when Total 
       Precipitation > 60.0 inches",
       xlab = "Year",
       ylab = "Density")
```

make a panel plot


```{r}
final_data %>% 
  drop_na(disaster) %>% 
  #group_by(location, disaster) %>% 
  ggplot(aes(x = disaster, fill = disaster))+
  geom_histogram(stat = "count" , position = "dodge", binwidth = 2) +
  theme(axis.text.x = element_text(angle = 90,  hjust = 1))+
  labs(title = "Frequency of Types of Disaster")


final_data %>% 
  drop_na(disaster, location) %>% 
  ggplot(aes(x = year, fill = location))+
  geom_bar()
```

```{r}

```

# do a violin plot

# box plot

# density plot
